# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('sum', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField()),
                ('blog_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.Blog')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
