# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
