# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blog_id',
            field=models.IntegerField(default=0),
        ),
    ]
