# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_blog_posts_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posts_words',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
