# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20170720_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posts_words',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
